receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 192
    spike_limit_mib: 32
  batch:
    timeout: 1s
    send_batch_size: 128
  filter/privacy:
    error_mode: propagate
    traces:
      span:
      - Len(links) > 0
      spanevent:
      - 'true'
  transform/privacy:
    error_mode: propagate
    trace_statements:
    - context: resource
      statements:
      - keep_keys(attributes, ["service.name", "service.namespace", "deployment.environment", "telemetry.sdk.name", "telemetry.sdk.language",
        "telemetry.sdk.version"])
    - &id001
      context: scope
      statements:
      - set(name, "creation.telemetry")
      - set(version, "")
      - keep_keys(attributes, [])
    - context: span
      statements:
      - keep_keys(attributes, ["http.route", "http.request.method", "http.method", "http.response.status_code", "http.status_code", "server.address",
        "server.port", "creation.operation", "creation.provider", "creation.stage", "creation.outcome", "creation.error_type", "creation.worker"])
      - set(name, "http.request")
      - set(name, attributes["creation.operation"]) where attributes["creation.operation"] != nil
      - set(status.message, "")
      - set(trace_state, "")
    metric_statements:
    - context: resource
      statements:
      - keep_keys(attributes, ["service.name", "service.namespace", "deployment.environment", "telemetry.sdk.name", "telemetry.sdk.language",
        "telemetry.sdk.version"])
    - *id001
    - context: datapoint
      statements:
      - keep_keys(attributes, ["operation", "outcome", "provider", "stage", "domain", "state", "http.route", "http.request.method", "http.method",
        "http.response.status_code", "http.status_code", "server.port", "net.peer.port", "net.host.port", "http.scheme", "http.flavor", "error.type"])
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 45s
    resource_to_telemetry_conversion:
      enabled: true
  otlphttp/tempo:
    endpoint: http://tempo:4318
    timeout: 2s
    sending_queue:
      queue_size: 256
    retry_on_failure:
      max_elapsed_time: 30s
service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - filter/privacy
      - transform/privacy
      - batch
      exporters:
      - otlphttp/tempo
    metrics:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - transform/privacy
      - batch
      exporters:
      - prometheus
