server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /positions/positions.yaml
clients:
- url: http://stf-loki:3100/loki/api/v1/push
scrape_configs:
- job_name: creation-operations
  static_configs:
  - targets:
    - localhost
    labels:
      job: creation-operations
      __path__: /var/lib/docker/containers/*/*-json.log
  pipeline_stages:
  - docker: {}
  - match:
      selector: '{job="creation-operations"} !~ "^.*app\\.observability\\.telemetry:operation:[0-9]+ - (\\{\"telemetry_version\":1,\"operation\":\"[a-z_.]+\",\"outcome\":\"(ok|error|cancelled)\",\"error_type\":\"[A-Za-z0-9_]*\",\"duration_seconds\":[0-9.e-]+,\"trace_id\":\"[a-f0-9]{32}\",\"span_id\":\"[a-f0-9]{16}\"\\})\\n?$"'
      action: drop
  - regex:
      expression: ^.*app\.observability\.telemetry:operation:[0-9]+ - (?P<payload>\{"telemetry_version":1,"operation":"[a-z_.]+","outcome":"(ok|error|cancelled)","error_type":"[A-Za-z0-9_]*","duration_seconds":[0-9.e-]+,"trace_id":"[a-f0-9]{32}","span_id":"[a-f0-9]{16}"\})\n?$
  - json:
      source: payload
      expressions:
        operation: operation
        outcome: outcome
  - labels:
      operation: null
      outcome: null
  - output:
      source: payload
